import { useLabels } from '../../api/hooks';
import type { Environment, Severity } from '../../api/types';
import { Field, Select, TextInput } from '../../components/Form';
import { formatMinutes, istInputToIso } from '../../lib/dates';
import { ENV_LABEL, ENVIRONMENTS, SEVERITIES } from '../../lib/labels';

export interface HeaderValues extends Record<string, unknown> {
  rca_date: string;
  company_name: string;
  project_name: string;
  project_owner_name: string;
  team_leader_name: string;
  ticket_id: string;
  severity: Severity | '';
  environment: Environment | '';
  incident_start: string; // datetime-local in IST
  detected_at: string;
  resolved_at: string;
  prepared_by_name: string;
  reviewed_by_name: string;
}

/** Form values -> API body (IST inputs become ISO with +05:30). */
export function headerToBody(v: HeaderValues) {
  return {
    rca_date: v.rca_date,
    company_name: v.company_name,
    project_name: v.project_name,
    project_owner_name: v.project_owner_name,
    team_leader_name: v.team_leader_name,
    ticket_id: v.ticket_id,
    severity: v.severity || undefined,
    environment: v.environment || undefined,
    incident_start: istInputToIso(v.incident_start) ?? undefined,
    detected_at: istInputToIso(v.detected_at),
    resolved_at: istInputToIso(v.resolved_at),
    prepared_by_name: v.prepared_by_name,
    reviewed_by_name: v.reviewed_by_name,
  };
}

interface Props {
  values: HeaderValues;
  set: <K extends keyof HeaderValues>(k: K, v: HeaderValues[K]) => void;
  errors: Record<string, string>;
  disabled: boolean;
  rcaNumber?: string;
  workspaceId?: string;
}

export function HeaderFields({ values, set, errors, disabled, rcaNumber, workspaceId }: Props) {
  const labels = useLabels(workspaceId);
  const detectMins =
    values.incident_start && values.detected_at
      ? Math.round((Date.parse(istInputToIso(values.detected_at)!) - Date.parse(istInputToIso(values.incident_start)!)) / 60000)
      : null;
  const text = (key: keyof HeaderValues, label: string, list?: string) => (
    <Field label={label} error={errors[key as string]} htmlFor={key as string}>
      <TextInput id={key as string} list={list} value={values[key] as string} disabled={disabled} onChange={(e) => set(key, e.target.value)} />
    </Field>
  );

  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
      <datalist id="company-options">
        {labels.data?.companies.map((c) => <option key={c} value={c} />)}
      </datalist>
      <datalist id="project-options">
        {labels.data?.projects.map((p) => <option key={p} value={p} />)}
      </datalist>
      <Field label="RCA number" hint="Generated by the system">
        <TextInput value={rcaNumber ?? 'Assigned on save'} disabled readOnly aria-label="RCA number" />
      </Field>
      <Field label="Date" error={errors.rca_date} htmlFor="rca_date">
        <TextInput id="rca_date" type="date" value={values.rca_date} disabled={disabled} onChange={(e) => set('rca_date', e.target.value)} />
      </Field>
      {text('ticket_id', 'Ticket / incident ID')}
      {text('company_name', 'Company (optional)', 'company-options')}
      {text('project_name', 'Project (optional)', 'project-options')}
      {text('project_owner_name', 'Project Owner')}
      {text('team_leader_name', 'RCA Team Leader')}
      <Field label="Severity" error={errors.severity} htmlFor="severity">
        <Select
          id="severity"
          value={values.severity}
          disabled={disabled}
          onChange={(e) => set('severity', e.target.value as Severity)}
          options={SEVERITIES.map((s) => ({ value: s, label: s }))}
        />
      </Field>
      <Field label="Environment" error={errors.environment} htmlFor="environment">
        <Select
          id="environment"
          value={values.environment}
          disabled={disabled}
          onChange={(e) => set('environment', e.target.value as Environment)}
          options={ENVIRONMENTS.map((s) => ({ value: s, label: ENV_LABEL[s] }))}
        />
      </Field>
      <Field label="Incident start (IST)" error={errors.incident_start} htmlFor="incident_start">
        <TextInput id="incident_start" type="datetime-local" value={values.incident_start} disabled={disabled} onChange={(e) => set('incident_start', e.target.value)} />
      </Field>
      <Field label="Detected at (IST)" error={errors.detected_at} htmlFor="detected_at">
        <TextInput id="detected_at" type="datetime-local" value={values.detected_at} disabled={disabled} onChange={(e) => set('detected_at', e.target.value)} />
      </Field>
      <Field label="Resolved at (IST)" error={errors.resolved_at} htmlFor="resolved_at">
        <TextInput id="resolved_at" type="datetime-local" value={values.resolved_at} disabled={disabled} onChange={(e) => set('resolved_at', e.target.value)} />
      </Field>
      <Field label="Time to detect" hint="Calculated: Detected at minus Incident start">
        <TextInput value={formatMinutes(detectMins)} disabled readOnly aria-label="Time to detect" />
      </Field>
      {text('prepared_by_name', 'Prepared by')}
      {text('reviewed_by_name', 'Reviewed by')}
    </div>
  );
}
