import { useProjects, useUsers } from '../../api/hooks';
import type { Environment, Severity } from '../../api/types';
import { Field, Select, TextInput } from '../../components/Form';
import { formatMinutes, istInputToIso } from '../../lib/dates';
import { ENV_LABEL, ENVIRONMENTS, SEVERITIES } from '../../lib/labels';

export interface HeaderValues extends Record<string, unknown> {
  rca_date: string;
  project_id: string;
  team_leader_id: string;
  ticket_id: string;
  severity: Severity | '';
  environment: Environment | '';
  incident_start: string; // datetime-local in IST
  detected_at: string;
  resolved_at: string;
  prepared_by: string;
  reviewed_by: string;
}

/** Form values -> API body (IST inputs become ISO with +05:30). */
export function headerToBody(v: HeaderValues) {
  return {
    rca_date: v.rca_date,
    project_id: v.project_id,
    team_leader_id: v.team_leader_id,
    ticket_id: v.ticket_id,
    severity: v.severity || undefined,
    environment: v.environment || undefined,
    incident_start: istInputToIso(v.incident_start) ?? undefined,
    detected_at: istInputToIso(v.detected_at),
    resolved_at: istInputToIso(v.resolved_at),
    prepared_by: v.prepared_by || null,
    reviewed_by: v.reviewed_by || null,
  };
}

interface Props {
  values: HeaderValues;
  set: <K extends keyof HeaderValues>(k: K, v: HeaderValues[K]) => void;
  errors: Record<string, string>;
  disabled: boolean;
  rcaNumber?: string;
}

export function HeaderFields({ values, set, errors, disabled, rcaNumber }: Props) {
  const projects = useProjects();
  const users = useUsers({ activeOnly: true });
  const project = projects.data?.find((p) => p.id === values.project_id);
  const leaders = (users.data ?? []).filter((u) => u.role === 'RCA_LEAD' || u.role === 'ADMIN' || u.id === values.team_leader_id);
  const userOptions = (users.data ?? []).map((u) => ({ value: u.id, label: u.name }));
  const detectMins =
    values.incident_start && values.detected_at
      ? Math.round((Date.parse(istInputToIso(values.detected_at)!) - Date.parse(istInputToIso(values.incident_start)!)) / 60000)
      : null;

  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
      <Field label="RCA number" hint="Generated by the system">
        <TextInput value={rcaNumber ?? 'Assigned on save'} disabled readOnly aria-label="RCA number" />
      </Field>
      <Field label="Date" error={errors.rca_date} htmlFor="rca_date">
        <TextInput id="rca_date" type="date" value={values.rca_date} disabled={disabled} onChange={(e) => set('rca_date', e.target.value)} />
      </Field>
      <Field label="Ticket / incident ID" error={errors.ticket_id} htmlFor="ticket_id">
        <TextInput id="ticket_id" value={values.ticket_id} disabled={disabled} onChange={(e) => set('ticket_id', e.target.value)} />
      </Field>
      <Field label="Project" error={errors.project_id} htmlFor="project_id">
        <Select
          id="project_id"
          value={values.project_id}
          disabled={disabled}
          onChange={(e) => set('project_id', e.target.value)}
          options={(projects.data ?? []).map((p) => ({ value: p.id, label: p.name }))}
        />
      </Field>
      <Field label="Company" hint="From the project">
        <TextInput value={project?.company.name ?? ''} disabled readOnly aria-label="Company" />
      </Field>
      <Field label="Project Owner" hint="From the project master">
        <TextInput value={project?.owner.name ?? ''} disabled readOnly aria-label="Project Owner" />
      </Field>
      <Field label="RCA Team Leader" error={errors.team_leader_id} htmlFor="team_leader_id">
        <Select
          id="team_leader_id"
          value={values.team_leader_id}
          disabled={disabled}
          onChange={(e) => set('team_leader_id', e.target.value)}
          options={leaders.map((u) => ({ value: u.id, label: u.name }))}
        />
      </Field>
      <Field label="Severity" error={errors.severity} htmlFor="severity">
        <Select
          id="severity"
          value={values.severity}
          disabled={disabled}
          onChange={(e) => set('severity', e.target.value as Severity)}
          options={SEVERITIES.map((s) => ({ value: s, label: s }))}
        />
      </Field>
      <Field label="Environment" error={errors.environment} htmlFor="environment">
        <Select
          id="environment"
          value={values.environment}
          disabled={disabled}
          onChange={(e) => set('environment', e.target.value as Environment)}
          options={ENVIRONMENTS.map((s) => ({ value: s, label: ENV_LABEL[s] }))}
        />
      </Field>
      <Field label="Incident start (IST)" error={errors.incident_start} htmlFor="incident_start">
        <TextInput
          id="incident_start"
          type="datetime-local"
          value={values.incident_start}
          disabled={disabled}
          onChange={(e) => set('incident_start', e.target.value)}
        />
      </Field>
      <Field label="Detected at (IST)" error={errors.detected_at} htmlFor="detected_at">
        <TextInput
          id="detected_at"
          type="datetime-local"
          value={values.detected_at}
          disabled={disabled}
          onChange={(e) => set('detected_at', e.target.value)}
        />
      </Field>
      <Field label="Resolved at (IST)" error={errors.resolved_at} htmlFor="resolved_at">
        <TextInput
          id="resolved_at"
          type="datetime-local"
          value={values.resolved_at}
          disabled={disabled}
          onChange={(e) => set('resolved_at', e.target.value)}
        />
      </Field>
      <Field label="Time to detect" hint="Calculated: Detected at minus Incident start">
        <TextInput value={formatMinutes(detectMins)} disabled readOnly aria-label="Time to detect" />
      </Field>
      <Field label="Prepared by" error={errors.prepared_by}>
        <Select value={values.prepared_by} disabled={disabled} onChange={(e) => set('prepared_by', e.target.value)} options={userOptions} />
      </Field>
      <Field label="Reviewed by" error={errors.reviewed_by}>
        <Select value={values.reviewed_by} disabled={disabled} onChange={(e) => set('reviewed_by', e.target.value)} options={userOptions} />
      </Field>
    </div>
  );
}
