import { randomUUID } from 'node:crypto';
import { text } from 'node:stream/consumers';
import { describe, expect, it } from 'vitest';
import { S3Storage } from '../src/storage/index.js';

/**
 * Runs against a real S3-compatible server when S3_TEST_ENDPOINT is set (CI starts one; locally e.g.
 * `docker run -p 9100:9090 -e initialBuckets=rca-test adobe/s3mock`).
 */
const endpoint = process.env.S3_TEST_ENDPOINT;

describe.skipIf(!endpoint)('S3 storage driver', () => {
  const s3 = new S3Storage(process.env.S3_TEST_BUCKET ?? 'rca-test', {
    region: 'us-east-1',
    endpoint,
    accessKeyId: process.env.S3_TEST_ACCESS_KEY ?? 'test',
    secretAccessKey: process.env.S3_TEST_SECRET_KEY ?? 'test',
    forcePathStyle: true,
  });

  it('puts, gets and deletes objects by random key', async () => {
    await s3.check();
    const key = `ws/${randomUUID()}/rca/${randomUUID()}/${randomUUID()}.txt`;
    await s3.put(key, Buffer.from('hello s3'), 'text/plain');
    expect(await text(await s3.get(key))).toBe('hello s3');
    await s3.delete(key);
    await expect(s3.get(key)).rejects.toThrow();
  });

  it('refuses keys that are not generated by the app', async () => {
    await expect(s3.put('../etc/passwd', Buffer.from('x'), 'text/plain')).rejects.toThrow(/Invalid storage key/);
  });
});
